### ISSUE TITLE
Error messages when importing MAPIE

### ISSUE THREAD

**Issue by ivan-marroquin** [scikit-learn-contrib/MAPIE#227]
**Describe the bug**

Running these commands produce the following error message:
a) from mapie.metrics import regression_coverage_score
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Python_3.8.10\lib\site-packages\mapie\__init__.py", line 1, in <module>
    from . import regression
  File "C:\Temp\Python_3.8.10\lib\site-packages\mapie\regression.py", line 12, in <module>
    from sklearn.utils.validation import (
ImportError: cannot import name '_check_y' from 'sklearn.utils.validation' (C:\Temp\Python_3.8.10\lib\site-packages\sklearn\utils\validation.py)

b) from mapie.regression import MapieRegressor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Python_3.8.10\lib\site-packages\mapie\__init__.py", line 1, in <module>
    from . import regression
  File "C:\Temp\Python_3.8.10\lib\site-packages\mapie\regression.py", line 12, in <module>
    from sklearn.utils.validation import (
ImportError: cannot import name '_check_y' from 'sklearn.utils.validation' (C:\Temp\Python_3.8.10\lib\site-packages\sklearn\utils\validation.py)

**To Reproduce**
1. In windows, open a DOS terminal and run python
2. use this command, from mapie.metrics import regression_coverage_score
3. use this command, from mapie.regression import MapieRegressor

**Expected behavior**
No error message when importing Mapie's functions

**Desktop (please complete the following information):**
 - OS: Windows 10
 - scikit-learn 0.22
 - MAPIE 0.5.0
 - numpy 1.19.5
 - Python 3.8.10
 
Best regards,
Ivan

**Comment by Sinnaeve** [comment]
I just had the same error with scikit-learn-0.24.2.
And it worker after upgrading to scikit-learn-1.1.3

**Comment by ivan-marroquin** [comment]
Hi @Sinnaeve 

Thanks a lot for the tip. It works fine.

Ivan
